name: Build

on:
  push:
    paths-ignore: [ "**.md" ]
    branches: [ "master", "release/**" ]
  pull_request:
    paths-ignore: [ "**.md" ]
    branches: [ "master", "release/**" ]

jobs:
  windows_build:
    name: "Build - Windows (MSVC)"
    runs-on: windows-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup MSBuild"
        uses: microsoft/setup-msbuild@v1
        with:
          vs-prerelease: true
          msbuild-architecture: x64

      - name: "Setup CMake"
        uses: lukka/get-cmake@v3.26.4

      - name: "Setup vcpkg"
        uses: lukka/run-vcpkg@v11

      - name: "Run CMake"
        uses: lukka/run-cmake@v10
